services:
  opencti-me2-event-aggregator:
    build:
      context: .
      target: event-aggregator
    restart: always
    container_name: opencti-me2-event-aggregator
    network_mode: "host"
    env_file:
      - ./event-aggregator/.env
    environment:
      - KAFKA_URL=${KAFKA_URL}
      - KAFKA_CONSUMER_GROUP_ID=${KAFKA_CONSUMER_GROUP_ID}
      - KAFKA_TOPIC=${KAFKA_TOPIC}
    command: ["-u", "kafka_consumer_sensor_event.py"]
  opencti-me2-event-parser:
    build:
      context: .
      target: event-parser
    container_name: opencti-me2-event-parser
    env_file:
      - ./event-parser/.env
    environment:
      - OPENCTI_URL=${OPENCTI_URL}
      - OPENCTI_API_KEY=${OPENCTI_API_KEY}
      - KAFKA_URL=${KAFKA_URL}
      - KAFKA_CONSUMER_GROUP_ID=${KAFKA_CONSUMER_GROUP_ID}
      - KAFKA_TOPIC=${KAFKA_TOPIC}
    networks:
      - opencti-me2-event-parser
    restart: always
    command: ["-u", "event_parser.py"]

networks:
  opencti-me2-event-parser:
    driver: bridge
